title: Namazu.tools
description: Tools and Guides provided by the Seat of Namazu Community and other FF14 groups
theme: just-the-docs

url: https://namazu.tools

aux_links:
  Discord: https://discord.gg/Cv5zgPRbby
  Github: https://github.com/The-Seat-of-Namazu/namazu.tools

favicon_ico: "/assets/images/favicon.ico"

color_scheme: namastyle

plugins:
  - jekyll-glossary_tooltip

callouts:
  tanks:
    title: Tanks
    color: blue
  healers:
    title: Healers
    color: green
  note:
    title: Note
    color: purple
  damage:
    title: Damage
    color: red
  warning:
    title: Warning
    color: red
  everyone:
    title: Everyone
    color: yellow