title: Namazu.tools
description: Tools and Guides provided by the Seat of Namazu Community and other FF14 groups
theme: just-the-docs

url: https://namazu.tools

aux_links:
  Discord: https://discord.gg/Cv5zgPRbby